### ISSUE TITLE
Merging `thesis_gemein_2022` into `TrixiAtmo.jl`

### ISSUE THREAD

**Issue by Arpit-Babbar** [trixi-framework/TrixiAtmo.jl#1]
In the branch https://github.com/trixi-framework/TrixiAtmo.jl/tree/ab_lucas, I am trying to add the results from https://github.com/NichtLucas/Trixi.jl/tree/thesis_gemein_2022 using Trixi as a dependency. 

Here is the $v_2$ velocity plot from the elixir https://github.com/trixi-framework/TrixiAtmo.jl/blob/ab_lucas/examples/elixir_moist_euler_nonhydrostatic_gravity_waves.jl

![image](https://github.com/trixi-framework/TrixiAtmo.jl/assets/7436733/c7b91233-6090-4cbe-af3d-e610c69511fa)

I have not made any changes to the internals of the code from https://github.com/trixi-framework/TrixiAtmo.jl/blob/ab_lucas/examples/elixir_moist_euler_nonhydrostatic_gravity_waves.jl, just added `import` and `using` as needed. We could do some more tests for validation. If things are okay, we can decide how to merge this into `main` (how to break into PRs and review).

**Comment by sloede** [comment]
Nice work! Can you please create a draft PR such that we can see how much code would have to be merged, in order to make an informed decision?

**Comment by tristanmontoya** [comment]
Completed in #2.
