### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by tristanmontoya** [trixi-framework/TrixiAtmo.jl#39]
As we discussed, the names **TrixiAtmos.jl** or **TrixiAtmosphere.jl** were preferred over the current name.

**Comment by sloede** [comment]
Actually, I have come to regret my initiative to discuss the package name. Maybe TrixiAtmo.jl is indeed the best variant, precisely because it is _not_ so annoyingly consistent and "proper" (= boring).

It is definitely easier to pronounce than with the "s" at the end, and TrixiAtmosphere would always be abbreviated in any informal conversation (oral or written) anyways

**Comment by tristanmontoya** [comment]
You make a great point that TrixiAtmosphere.jl would inevitably get abbreviated either to TrixiAtmo or TrixiAtmos, and I agree with the pronunciation aspect! I am somewhat less inclined to changing the name now, but maybe we should keep this issue open in case there is any further discussion regarding the name of the package.

**Comment by sloede** [comment]
> but maybe we should keep this issue open in case there is any further discussion regarding the name of the package.

We could do this, but really, unless we find out that TrixiAtmo is secretly a Columbian swear word that @amrueda has not told us about, I don't see a reason why we'd ever change it. Let's make a decision - whatever it is - and close this issue (it'll still be there, just one additional click away)

**Comment by tristanmontoya** [comment]
Seeing as @sloede was the one who had previously raised the strongest objection to "TrixiAtmo" and nobody seems to feel too strongly in favour of a different name, I am making the decision to keep the name and close this issue for now. If anyone has a nice idea for a better name, or a good reason to switch to one of those previously suggested, feel free to raise the issue again, as I am still open to changing it.
