### ISSUE TITLE
Support for Trixi.jl versions < 0.9?

### ISSUE THREAD

**Issue by tristanmontoya** [trixi-framework/TrixiAtmo.jl#43]
In https://github.com/trixi-framework/Trixi.jl/pull/2037, the unused parameter `initial_condition` was removed from `rhs!`. In my implementation of a new `rhs!` method for the covariant solver in #31, should I have a second version that takes `initial_condition` to maintain compatibility with older Trixi.jl versions? Or should we just change the compat in Project.toml to only be 0.9? I have no problem either way but I was wondering if there's any good reason to support such earlier versions of Trixi.jl.

**Comment by benegee** [comment]
Perfectly fine with me!
As long as we do not have any releases, there seems to be no reason to be backward compatible.

**Comment by ranocha** [comment]
Yes, I agree - just update the compatibility section of the Project.toml accordingly

**Comment by tristanmontoya** [comment]
Support for versions < 0.9 is now dropped as of #47.
